name: "Upload to Dropbox"
description: "Upload a file to Dropbox"
author: "Deka"
branding:
  icon: upload-cloud
  color: blue
inputs:
  dropbox_access_token:
    required: true
    description: "Dropbox access token"
  file:
    required: true
    description: "File to upload to Dropbox"
  path:
    required: true
    description: "Destination path for upload"
runs:
  using: "node12"
  main: "dist/index.js"
